server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: accept
          uri: http://localhost:8081
          predicates:
            - Path=/acceptProcessings/** 
        - id: repair
          uri: http://localhost:8082
          predicates:
            - Path=/repairProcessings/**
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /logs/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: accept
          uri: http://acceptprocessings:8080
          predicates:
            - Path=/acceptProcessings/** 
        - id: repair
          uri: http://repairprocessings:8080
          predicates:
            - Path=/repairProcessings/**
        - id: mypage
          uri: http://logs:8080
          predicates:
            - Path= /logs/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
server:
  port: 8080
